# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MTSI Developers Blog
email: developers@mitsi.com
description: > # this means to ignore newlines until "baseurl:"
   MTSI is based in Richardson, Texas and provides the Lynx series of security
   products, as well as contract engineering and electronics manufacturing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://microtechnology-services.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  microtechnology-services

# Build settings
markdown: kramdown

gems:
   - jekyll-sitemap
